# Generated by Django 5.2.12 on 2026-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='content_type',
            field=models.CharField(choices=[('movie', 'Pelicula'), ('series', 'Serie')], default='movie', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='cover_file',
            field=models.FileField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL del video (opcional si subes archivo local)'),
        ),
    ]
