# Generated by Django 5.2.12 on 2026-03-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_favorite_playbackprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cover_file',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL publica del video en Supabase Storage'),
        ),
    ]
