# Generated by Django 5.2.12 on 2026-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_cover_file_remove_movie_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.CharField(blank=True, help_text='URL publica o ruta local publicada del video', max_length=200),
        ),
    ]
