# Generated by Django 5.2.12 on 2026-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_upload_duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_upload_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_upload_size_bytes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
