# Generated by Django 5.2.12 on 2026-04-14 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_watchparty_watchpartymember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchparty',
            name='control_mode',
            field=models.CharField(choices=[('host', 'Solo host'), ('shared', 'Control compartido')], default='host', max_length=12),
        ),
        migrations.AddField(
            model_name='watchpartymember',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WatchPartyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='movies.watchparty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_party_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
