# Generated by Django 5.2.12 on 2026-04-28 07:17

from django.db import migrations, models


def initialize_processing_status(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    Movie.objects.exclude(video_url='').update(status='listo', processing_step='finalizado')
    Movie.objects.filter(video_url='').update(status='subiendo', processing_step='')


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_watchparty_control_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='processing_step',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('subiendo', 'Subiendo'), ('procesando', 'Procesando'), ('listo', 'Listo'), ('error', 'Error')], default='subiendo', max_length=20),
        ),
        migrations.RunPython(initialize_processing_status, migrations.RunPython.noop),
    ]
