# Generated by Codex on 2026-04-29

from django.db import migrations, models


def initialize_processing_progress(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    Movie.objects.filter(status='listo').update(
        processing_stage='finalizado',
        processing_progress=100,
    )
    Movie.objects.filter(status='error').update(
        processing_stage='error',
        processing_progress=0,
    )
    Movie.objects.filter(video_url='').exclude(status='error').update(
        processing_stage='pendiente',
        processing_progress=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_processing_step_movie_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='processing_stage',
            field=models.CharField(default='pendiente', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='processing_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(initialize_processing_progress, migrations.RunPython.noop),
    ]
