# Generated by Django 5.2.12 on 2026-05-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_thumbnail_previews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='thumbnail_interval',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
